# Generated by Django 6.0.3 on 2026-03-19 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'terms',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('target_scope', models.CharField(choices=[('all', 'All'), ('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=20)),
                ('max_courses', models.PositiveIntegerField(default=0)),
                ('allow_drop', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='rounds.term')),
            ],
            options={
                'db_table': 'rounds',
                'ordering': ['-id'],
                'unique_together': {('term', 'name')},
            },
        ),
    ]
