# Generated by Codex on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rounds", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="round",
            index=models.Index(fields=["term", "enabled"], name="round_term_enabled_idx"),
        ),
        migrations.AddIndex(
            model_name="round",
            index=models.Index(fields=["enabled", "start_at", "end_at"], name="round_enabled_window_idx"),
        ),
    ]
