# Generated by Codex on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["section", "status"], name="enroll_section_status_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["student", "round", "status"], name="enr_stu_rnd_stat_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["student", "status"], name="enroll_student_status_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["round", "status"], name="enroll_round_status_idx"),
        ),
    ]
