# Generated by Codex on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="section",
            index=models.Index(fields=["term", "course"], name="section_term_course_idx"),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(fields=["term", "teacher"], name="section_term_teacher_idx"),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(fields=["term", "weekday", "start_time"], name="section_term_schedule_idx"),
        ),
    ]
