# Generated by Codex on 2026-03-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rounds", "0001_initial"),
        ("courses", "0002_section_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="rounds.round",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("round", "course", "name")},
        ),
        migrations.RemoveIndex(
            model_name="section",
            name="section_term_course_idx",
        ),
        migrations.RemoveIndex(
            model_name="section",
            name="section_term_teacher_idx",
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(fields=["round", "course"], name="section_round_course_idx"),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(fields=["round", "teacher"], name="section_round_teacher_idx"),
        ),
    ]
