# Generated by Codex on 2026-03-24

from django.db import migrations


def backfill_section_round(apps, schema_editor):
    Section = apps.get_model("courses", "Section")
    CourseApplication = apps.get_model("applications", "CourseApplication")

    pending_updates = {}
    queryset = CourseApplication.objects.exclude(linked_section_id__isnull=True).exclude(round_id__isnull=True)

    for application in queryset.iterator():
        pending_updates.setdefault(application.linked_section_id, application.round_id)

    if not pending_updates:
        return

    sections = Section.objects.filter(id__in=pending_updates.keys(), round_id__isnull=True)
    for section in sections.iterator():
        section.round_id = pending_updates.get(section.id)
        section.save(update_fields=["round"])


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_courseapplication_round"),
        ("courses", "0003_section_round"),
    ]

    operations = [
        migrations.RunPython(backfill_section_round, migrations.RunPython.noop),
    ]
