# Generated by Codex on 2026-03-24

import django.db.models.deletion
from django.db import migrations, models


def fill_missing_section_round(apps, schema_editor):
    Section = apps.get_model("courses", "Section")
    CourseApplication = apps.get_model("applications", "CourseApplication")
    Enrollment = apps.get_model("enrollments", "Enrollment")
    Round = apps.get_model("rounds", "Round")

    unresolved_ids = []

    for section in Section.objects.filter(round_id__isnull=True).order_by("id").iterator():
        application_round_ids = list(
            CourseApplication.objects.filter(linked_section_id=section.id)
            .exclude(round_id__isnull=True)
            .values_list("round_id", flat=True)
            .distinct()
        )
        if len(application_round_ids) == 1:
            section.round_id = application_round_ids[0]
            section.save(update_fields=["round"])
            continue

        enrollment_round_ids = list(
            Enrollment.objects.filter(section_id=section.id)
            .exclude(round_id__isnull=True)
            .values_list("round_id", flat=True)
            .distinct()
        )
        if len(enrollment_round_ids) == 1:
            section.round_id = enrollment_round_ids[0]
            section.save(update_fields=["round"])
            continue

        term_round_ids = list(
            Round.objects.filter(term_id=section.term_id)
            .values_list("id", flat=True)
            .order_by("id")
        )
        if len(term_round_ids) == 1:
            section.round_id = term_round_ids[0]
            section.save(update_fields=["round"])
            continue

        unresolved_ids.append(section.id)

    if unresolved_ids:
        raise RuntimeError(f"Sections still missing round binding: {unresolved_ids}")


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_courseapplication_round"),
        ("enrollments", "0001_initial"),
        ("rounds", "0001_initial"),
        ("courses", "0004_backfill_section_round"),
    ]

    operations = [
        migrations.RunPython(fill_missing_section_round, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="section",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="rounds.round",
            ),
        ),
    ]
